### ISSUE TITLE
Last value offset

### ISSUE THREAD

**Issue by Yllelder** [winne27/flot-valuelabels#18] opened 2020-12-17 01:32 UTC
I don't understand why the last value on the chart is shown shifted to the left, instead of above the border. The first value does, even the highest values overlap with the top border.

![example](https://imgur.com/hxrrjAd.png)

I tried to use the _xoffsetLast_ option to move it manually but it doesn't work.

This is my chart code:
```javascript
var data = [[1, 8], [2, 8], [3, 8], [4, 9], [5, 9], [6, 9], [7, 10], [8, 10], [9, 9], [10, 6], [11, 2], [12, 4], [13, 2]];

var dataset = [
		{
			data: data,
			lines: {show: true, lineWidth: 3},
			curvedLines: {apply: true, monotonicFit: true}
		},
		{
			data: data,
			points: {show: true, radius: 13},
			 valueLabels: {
			 	show: true,
			 	yoffset: 23,
			 	fontcolor: '#2C2C2C',
			 	font: "11pt Roboto",
			 },
		}
	];

var options = {

	series: { curvedLines: {active: true} },

	yaxis: { show: false },

	grid: {
	 	margin: 15,
	}
};

$(document).ready(function () {
	$.plot($("#grafica"), dataset, options);
});
```

**Comment by winne27** [comment] 2021-10-08 17:13
Sorry, for the long response time

**Comment by winne27** [comment] 2021-10-08 17:16
Sorry for the long response time and the confusion with close and reopen. I have found a solution and will publish it in the next few days.

**Comment by winne27** [comment] 2021-10-08 18:26
The problem is now fixed. Check it please!

**Closed as completed** 2021-10-08 18:27 UTC
